DROP DATABASE IF EXISTS greatBayDB;

CREATE DATABASE greatBayDB;

USE greatBayDB;

CREATE TABLE bid (
  id INT NOT NULL AUTO_INCREMENT,
  postItem VARCHAR(100) NOT NULL,
  bid INTEGER (100) NOT NULL,
  category VARCHAR(100) NULL,
  PRIMARY KEY (id)
);

SELECT * FROM bid
